### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by itsdarrylnorris** [CashWilliams/drupack#1]
## Problem

This shell script does not contain any comments.
## Solution

Add comments to identify the different areas of this shell script
## Resource to accomplish this:

http://www.tldp.org/LDP/Bash-Beginners-Guide/html/sect_02_02.html

**Comment by CashWilliams** [comment]
Seems like overkill on such a simple script.... but ok https://github.com/CashWilliams/drupack/commit/7bf98ae43109dd81f5861bbf4ccc96c64e3c208f
